version: '3.5'
services:
  venom-bot:
    hostname: venom-bot
    container_name: venom-bot
    build:
      context: .
      shm_size: '1gb' 
    shm_size: '1gb'
    command: npm start
    environment:
      - NODE_ENV=local
    volumes:
      - ./:/server
    ports:
      - 3001:3001